# -*- coding: utf-8 -*-
"""web_scrapping_portfolio_project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgBfNnfl2xm4oqVGG8-ARr-ULwmx2Ji1
"""

# 1. Install required tools
#!pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup

# 2. Define the webpage URL
url = "http://books.toscrape.com/"

# 3. Send a request to fetch the web page
response = requests.get(url)

# 4. Check if the website responded successfully (HTTP Status 200 means OK)
print("Status Code:", response.status_code)
print("Page downloaded successfully!")

# 1. Parse the downloaded HTML text using BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# 2. Find all book elements (each book is inside an <article class="product_pod"> tag)
book_elements = soup.find_all("article", class_="product_pod")

# 3. Print how many books were found on the page
print("Total books found on page 1:", len(book_elements))

# 1. Create an empty list to store the extracted book details
books_list = []

# 2. Loop through each of the 20 book elements
for book in book_elements:
    # Extract book title from the 'title' attribute inside the <a> tag
    title = book.h3.a["title"]

    # Extract raw price text (e.g., 'Â£51.77')
    raw_price = book.find("p", class_="price_color").text

    # Clean the price: remove 'Â' and '£' characters, then strip extra spaces
    clean_price_text = raw_price.replace("Â", "").replace("£", "").strip()

    # Convert cleaned text to a decimal number (float)
    clean_price = float(clean_price_text)

    # Append details as a dictionary
    books_list.append({
        "title": title,
        "price_gbp": clean_price
    })

# 3. Print the first 3 items to check the result
print("First 3 books extracted:")
print(books_list[:3])

import pandas as pd

# 1. Convert the list of book dictionaries into a DataFrame
df_books = pd.DataFrame(books_list)

# 2. Display the top 5 rows of the DataFrame
df_books.head()

import sqlite3

# 1. Connect to a SQLite database file (it creates the file if it doesn't exist)
conn = sqlite3.connect("scraped_data.db")

# 2. Save the DataFrame into a database table named 'scraped_books'
df_books.to_sql("scraped_books", conn, if_exists="replace", index=False)

# 3. Verify that the data was written correctly by querying the database back
verification_df = pd.read_sql_query("SELECT * FROM scraped_books LIMIT 5;", conn)

# 4. Close the database connection
conn.close()

# 5. Display the verified data retrieved from SQLite
verification_df

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. List to store books across all pages
all_books = []

# 2. Loop through the first 3 pages
for page in range(1, 4):
    # Construct the URL for each page
    page_url = f"http://books.toscrape.com/catalogue/page-{page}.html"

    # Send HTTP request
    response = requests.get(page_url)

    # Parse HTML
    soup = BeautifulSoup(response.text, "html.parser")
    book_elements = soup.find_all("article", class_="product_pod")

    # Extract details for each book on the current page
    for book in book_elements:
        title = book.h3.a["title"]
        raw_price = book.find("p", class_="price_color").text
        clean_price = float(raw_price.replace("Â", "").replace("£", "").strip())

        all_books.append({
            "title": title,
            "price_gbp": clean_price,
            "page_number": page
        })

# 3. Convert all extracted books into a single DataFrame
df_multi_page = pd.DataFrame(all_books)

# 4. Print total books collected and preview counts per page
print(f"Total books collected across 3 pages: {len(df_multi_page)}")
print("\nBooks collected per page:")
print(df_multi_page["page_number"].value_counts())

import sqlite3

# 1. Connect to our SQLite database file
conn = sqlite3.connect("scraped_data.db")

# 2. Save the multi-page DataFrame into the 'scraped_books' table
df_multi_page.to_sql("scraped_books", conn, if_exists="replace", index=False)

# 3. Count total records stored in the database table using SQL
sql_count = pd.read_sql_query("SELECT COUNT(*) AS total_records FROM scraped_books;", conn)

# 4. Fetch a sample from page 2 to verify multi-page data storage
sample_page_2 = pd.read_sql_query("SELECT * FROM scraped_books WHERE page_number = 2 LIMIT 3;", conn)

# 5. Close database connection
conn.close()

# 6. Display verification results
print(sql_count)
print("\nSample records from Page 2:")
sample_page_2

# 1. Export DataFrame to a clean CSV file
df_multi_page.to_csv("scraped_books_data.csv", index=False)

print("Project completed successfully!")
print("1. File 'scraped_books_data.csv' saved.")
print("2. File 'scraped_data.db' ready in your Colab files panel.")